# Generated by Django 5.0.14 on 2026-07-14 22:58

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='JPEG/PNG/WebP, up to 5MB. Auto-resized to 512px.', null=True, upload_to=accounts.validators.ProfilePictureUploadPath(), validators=[accounts.validators.validate_image_file_size]),
        ),
    ]
